"""Autoconf substitutions for bash 5.2.37 on x86_64 Debian trixie (glibc).

Stands in for ./configure, which probes the host compiler and libc. Values are
what autoconf resolves for this target triple with the flags debian/rules
passes (--enable-largefile --without-bash-malloc --with-installed-readline),
plus SONiC's plugin patch, whose BASH_SHELL_EXECVE_PLUGIN entry is what makes
bash-tacplus loadable.

Verified byte-identical to a real configure run apart from the banner comment.
"""

# `#undef NAME` lines in config.h.in that configure turns into `#define`.
# Anything absent stays #undef. An empty value emits a bare `#define NAME`.
#
# USING_BASH_MALLOC is deliberately NOT here: debian/rules passes
# --without-bash-malloc, so bash uses glibc's allocator and lib/malloc/ is not
# built. (Verified: Make's deb contains none of lib/malloc's diagnostic
# strings.) The stale tree under src/bash/bash-5.2.37/ has it enabled because
# that tree was configured without Debian's flags.
CONFIG_DEFINES = {
    "JOB_CONTROL": "1",
    "BASH_SHELL_EXECVE_PLUGIN": "1",
    "ALIAS": "1",
    "PUSHD_AND_POPD": "1",
    "BRACE_EXPANSION": "1",
    "READLINE": "1",
    "BANG_HISTORY": "1",
    "HISTORY": "1",
    "HELP_BUILTIN": "1",
    "RESTRICTED_SHELL": "1",
    "PROCESS_SUBSTITUTION": "1",
    "PROMPT_STRING_DECODE": "1",
    "SELECT_COMMAND": "1",
    "COMMAND_TIMING": "1",
    "ARRAY_VARS": "1",
    "DPAREN_ARITHMETIC": "1",
    "EXTENDED_GLOB": "1",
    "EXTGLOB_DEFAULT": "0",
    "COND_COMMAND": "1",
    "ARITH_FOR_COMMAND": "1",
    "NETWORK_REDIRECTIONS": "1",
    "PROGRAMMABLE_COMPLETION": "1",
    "DEBUGGER": "1",
    "MEMSCRAMBLE": "1",
    "CASEMOD_ATTRS": "1",
    "CASEMOD_EXPANSIONS": "1",
    "GLOBASCII_DEFAULT": "1",
    "FUNCTION_IMPORT": "1",
    "ENABLE_NLS": "1",
    "restrict": "__restrict__",
    "HAVE_STRINGIZE": "1",
    "HAVE_LONG_DOUBLE": "1",
    "PROTOTYPES": "1",
    "__PROTOTYPES": "1",
    "HAVE_LONG_LONG_INT": "1",
    "HAVE_UNSIGNED_LONG_LONG_INT": "1",
    "SIZEOF_INT": "4",
    "SIZEOF_LONG": "8",
    "SIZEOF_CHAR_P": "8",
    "SIZEOF_SIZE_T": "8",
    "SIZEOF_DOUBLE": "8",
    "SIZEOF_INTMAX_T": "8",
    "SIZEOF_LONG_LONG": "8",
    "SIZEOF_WCHAR_T": "4",
    "_GNU_SOURCE": "1",
    "__EXTENSIONS__": "1",
    "_ALL_SOURCE": "1",
    "_POSIX_PTHREAD_SEMANTICS": "1",
    "_TANDEM_SOURCE": "1",
    "HAVE_ALLOCA": "1",
    "HAVE_ALLOCA_H": "1",
    "MAJOR_IN_SYSMACROS": "1",
    "bits16_t": "short",
    "u_bits16_t": "unsigned short",
    "bits32_t": "int",
    "u_bits32_t": "unsigned int",
    "bits64_t": "char *",
    "HAVE_MBSTATE_T": "1",
    "HAVE_QUAD_T": "1",
    "HAVE_WCHAR_T": "1",
    "HAVE_WCTYPE_T": "1",
    "HAVE_WINT_T": "1",
    "RLIMTYPE": "rlim_t",
    "GETGROUPS_T": "gid_t",
    "HAVE_DECL_SYS_SIGLIST": "0",
    "HAVE_SYS_ERRLIST": "1",
    "HAVE_STRUCT_DIRENT_D_INO": "1",
    "HAVE_STRUCT_DIRENT_D_FILENO": "1",
    "FIONREAD_IN_SYS_IOCTL": "1",
    "GWINSZ_IN_SYS_IOCTL": "1",
    "STRUCT_WINSIZE_IN_SYS_IOCTL": "1",
    "TERMIOS_LDISC": "1",
    "TERMIO_LDISC": "1",
    "HAVE_STRUCT_STAT_ST_BLOCKS": "1",
    "HAVE_STRUCT_TM_TM_ZONE": "1",
    "HAVE_TM_ZONE": "1",
    "HAVE_TIMEVAL": "1",
    "HAVE_STRUCT_TIMEZONE": "1",
    "WEXITSTATUS_OFFSET": "8",
    "HAVE_STRUCT_TIMESPEC": "1",
    "TIME_H_DEFINES_STRUCT_TIMESPEC": "1",
    "HAVE_STRUCT_STAT_ST_ATIM_TV_NSEC": "1",
    "TYPEOF_STRUCT_STAT_ST_ATIM_IS_STRUCT_TIMESPEC": "1",
    "HAVE_GETPW_DECLS": "1",
    "HAVE_DECL_AUDIT_USER_TTY": "1",
    "HAVE_DECL_CONFSTR": "1",
    "HAVE_DECL_PRINTF": "1",
    "HAVE_DECL_SBRK": "1",
    "HAVE_DECL_STRCPY": "1",
    "HAVE_DECL_STRSIGNAL": "1",
    "HAVE_DECL_STRTOLD": "1",
    "HAVE_DECL_STRTOIMAX": "1",
    "HAVE_DECL_STRTOL": "1",
    "HAVE_DECL_STRTOLL": "1",
    "HAVE_DECL_STRTOUL": "1",
    "HAVE_DECL_STRTOULL": "1",
    "HAVE_DECL_STRTOUMAX": "1",
    "GETPGRP_VOID": "1",
    "PGRP_PIPE": "1",
    "ULIMIT_MAXFDS": "1",
    "CAN_REDEFINE_GETENV": "1",
    "HAVE_STD_PUTENV": "1",
    "HAVE_STD_UNSETENV": "1",
    "HAVE_PRINTF_A_FORMAT": "1",
    "HAVE_LANGINFO_CODESET": "1",
    "HAVE_HASH_BANG_EXEC": "1",
    "HAVE_DEV_FD": "1",
    "DEV_FD_PREFIX": "\"/dev/fd/\"",
    "HAVE_DEV_STDIN": "1",
    "ICONV_CONST": "",
    "HAVE_POSIX_SIGNALS": "1",
    "HAVE_ARC4RANDOM": "1",
    "HAVE_ASPRINTF": "1",
    "HAVE_BCOPY": "1",
    "HAVE_BZERO": "1",
    "HAVE_CHOWN": "1",
    "HAVE_CONFSTR": "1",
    "HAVE_DLCLOSE": "1",
    "HAVE_DLOPEN": "1",
    "HAVE_DLSYM": "1",
    "HAVE_DPRINTF": "1",
    "HAVE_DUP2": "1",
    "HAVE_EACCESS": "1",
    "HAVE_FACCESSAT": "1",
    "HAVE_FCNTL": "1",
    "HAVE_FNMATCH": "1",
    "FNMATCH_EQUIV_FALLBACK": "0",
    "HAVE___FPURGE": "1",
    "HAVE_DECL_FPURGE": "0",
    "HAVE_GETADDRINFO": "1",
    "HAVE_GETCWD": "1",
    "HAVE_GETENTROPY": "1",
    "HAVE_GETDTABLESIZE": "1",
    "HAVE_GETGROUPS": "1",
    "HAVE_GETHOSTBYNAME": "1",
    "HAVE_GETHOSTNAME": "1",
    "HAVE_GETPAGESIZE": "1",
    "HAVE_GETPEERNAME": "1",
    "HAVE_GETPWENT": "1",
    "HAVE_GETPWNAM": "1",
    "HAVE_GETPWUID": "1",
    "HAVE_GETRANDOM": "1",
    "HAVE_GETRLIMIT": "1",
    "HAVE_GETRUSAGE": "1",
    "HAVE_GETSERVBYNAME": "1",
    "HAVE_GETSERVENT": "1",
    "HAVE_GETTIMEOFDAY": "1",
    "HAVE_ICONV": "1",
    "HAVE_IMAXDIV": "1",
    "HAVE_INET_ATON": "1",
    "HAVE_ISASCII": "1",
    "HAVE_ISBLANK": "1",
    "HAVE_ISGRAPH": "1",
    "HAVE_ISPRINT": "1",
    "HAVE_ISSPACE": "1",
    "HAVE_ISWCTYPE": "1",
    "HAVE_ISWLOWER": "1",
    "HAVE_ISWUPPER": "1",
    "HAVE_ISXDIGIT": "1",
    "HAVE_KILL": "1",
    "HAVE_KILLPG": "1",
    "HAVE_LSTAT": "1",
    "HAVE_MBRLEN": "1",
    "HAVE_MBRTOWC": "1",
    "HAVE_MBSNRTOWCS": "1",
    "HAVE_MBSRTOWCS": "1",
    "HAVE_MEMMOVE": "1",
    "HAVE_MEMSET": "1",
    "HAVE_MKDTEMP": "1",
    "HAVE_MKFIFO": "1",
    "HAVE_MKSTEMP": "1",
    "HAVE_PATHCONF": "1",
    "HAVE_PSELECT": "1",
    "HAVE_PUTENV": "1",
    "HAVE_RAISE": "1",
    "HAVE_RANDOM": "1",
    "HAVE_READLINK": "1",
    "HAVE_REGCOMP": "1",
    "HAVE_REGEXEC": "1",
    "HAVE_RENAME": "1",
    "HAVE_SBRK": "1",
    "HAVE_SELECT": "1",
    "HAVE_SETENV": "1",
    "HAVE_SETITIMER": "1",
    "HAVE_SETLINEBUF": "1",
    "HAVE_SETLOCALE": "1",
    "HAVE_DECL_SETREGID": "1",
    "HAVE_SETRESGID": "1",
    "HAVE_SETRESUID": "1",
    "HAVE_SETVBUF": "1",
    "HAVE_SIGINTERRUPT": "1",
    "HAVE_POSIX_SIGSETJMP": "1",
    "HAVE_SNPRINTF": "1",
    "HAVE_STRCASECMP": "1",
    "HAVE_STRCASESTR": "1",
    "HAVE_STRCHR": "1",
    "HAVE_STRCHRNUL": "1",
    "HAVE_STRCOLL": "1",
    "HAVE_STRERROR": "1",
    "HAVE_STRFTIME": "1",
    "HAVE_STRNLEN": "1",
    "HAVE_STRPBRK": "1",
    "HAVE_STRSTR": "1",
    "HAVE_STRTOD": "1",
    "HAVE_STRTOIMAX": "1",
    "HAVE_STRTOL": "1",
    "HAVE_STRTOLL": "1",
    "HAVE_STRTOUL": "1",
    "HAVE_STRTOULL": "1",
    "HAVE_STRTOUMAX": "1",
    "HAVE_STRSIGNAL": "1",
    "HAVE_SYSCONF": "1",
    "HAVE_SYSLOG": "1",
    "HAVE_TCGETATTR": "1",
    "HAVE_TCGETPGRP": "1",
    "HAVE_TIMES": "1",
    "HAVE_TOWLOWER": "1",
    "HAVE_TOWUPPER": "1",
    "HAVE_TTYNAME": "1",
    "HAVE_TZSET": "1",
    "HAVE_ULIMIT": "1",
    "HAVE_UNAME": "1",
    "HAVE_UNSETENV": "1",
    "HAVE_VASPRINTF": "1",
    "HAVE_VPRINTF": "1",
    "HAVE_VSNPRINTF": "1",
    "HAVE_WAITPID": "1",
    "HAVE_WAIT3": "1",
    "HAVE_WCRTOMB": "1",
    "HAVE_WCSCOLL": "1",
    "HAVE_WCSDUP": "1",
    "HAVE_WCTYPE": "1",
    "HAVE_WCSWIDTH": "1",
    "HAVE_WCWIDTH": "1",
    "WCWIDTH_BROKEN": "1",
    "HAVE_ARPA_INET_H": "1",
    "HAVE_DIRENT_H": "1",
    "HAVE_DLFCN_H": "1",
    "HAVE_GRP_H": "1",
    "HAVE_INTTYPES_H": "1",
    "HAVE_LANGINFO_H": "1",
    "HAVE_LIBAUDIT_H": "1",
    "HAVE_LIMITS_H": "1",
    "HAVE_LOCALE_H": "1",
    "HAVE_NETDB_H": "1",
    "HAVE_NETINET_IN_H": "1",
    "HAVE_PWD_H": "1",
    "HAVE_REGEX_H": "1",
    "HAVE_STDLIB_H": "1",
    "HAVE_STDARG_H": "1",
    "HAVE_STRING_H": "1",
    "HAVE_STRINGS_H": "1",
    "HAVE_MEMORY_H": "1",
    "HAVE_STDBOOL_H": "1",
    "HAVE_STDDEF_H": "1",
    "HAVE_STDINT_H": "1",
    "HAVE_SYSLOG_H": "1",
    "HAVE_SYS_FILE_H": "1",
    "HAVE_SYS_IOCTL_H": "1",
    "HAVE_SYS_MMAN_H": "1",
    "HAVE_SYS_PARAM_H": "1",
    "HAVE_SYS_RANDOM_H": "1",
    "HAVE_SYS_RESOURCE_H": "1",
    "HAVE_SYS_SELECT_H": "1",
    "HAVE_SYS_SOCKET_H": "1",
    "HAVE_SYS_STAT_H": "1",
    "HAVE_SYS_TIME_H": "1",
    "HAVE_SYS_TIMES_H": "1",
    "HAVE_SYS_TYPES_H": "1",
    "HAVE_SYS_WAIT_H": "1",
    "HAVE_TERMCAP_H": "1",
    "HAVE_TERMIO_H": "1",
    "HAVE_TERMIOS_H": "1",
    "HAVE_ULIMIT_H": "1",
    "HAVE_UNISTD_H": "1",
    "HAVE_WCHAR_H": "1",
    "HAVE_WCTYPE_H": "1",
    "HAVE_LIBDL": "1",
    "TRANSLATABLE_STRINGS": "1",
    "HAVE_ARGZ_H": "1",
    "HAVE_ERRNO_H": "1",
    "HAVE_FCNTL_H": "1",
    "HAVE_MALLOC_H": "1",
    "HAVE_STDIO_EXT_H": "1",
    "HAVE_DCGETTEXT": "1",
    "HAVE_LOCALECONV": "1",
    "HAVE_MEMPCPY": "1",
    "HAVE_MMAP": "1",
    "HAVE_MREMAP": "1",
    "HAVE_MUNMAP": "1",
    "HAVE_STPCPY": "1",
    "HAVE_STRCSPN": "1",
    "HAVE_STRDUP": "1",
    "HAVE___ARGZ_COUNT": "1",
    "HAVE___ARGZ_NEXT": "1",
    "HAVE___ARGZ_STRINGIFY": "1",
}

# Macros config.h.in already spells as `#define`, either bare or with an
# upstream placeholder value; configure rewrites these in place.
CONFIG_REDEFINES = {
    "COND_REGEXP": "1",
    "COPROCESS_SUPPORT": "1",
    "DEFAULT_MAIL_DIRECTORY": "\"/var/mail\"",
}

# configure's only substitution in pathnames.h.in:
#   DEBUGGER_START_FILE='${datadir}/bashdb/bashdb-main.inc'
# with datadir = $prefix/share and debian/rules passing --prefix=/usr. Verified
# against the string embedded in Make's bash_5.2.37-2_amd64.deb.
DEBUGGER_START_FILE = "/usr/share/bashdb/bashdb-main.inc"

# Makefile's `Version = 5.2` / `RELSTATUS = release`, consumed by
# support/mkversion.sh.
VERSION_BASE = "5.2"

RELSTATUS = "release"

# builtins/psize.sh writes pipesize.h by actually filling a pipe on the build
# machine — a host probe with no place in a hermetic build. 65536 is Linux's
# default pipe buffer (16 pages), and matches what Make's build measured.
PIPESIZE = 65536

# Makefile.in's SYSTEM_FLAGS + LOCALE_DEFS, which configure fills from the host
# triple and --prefix. conftypes.h requires all four CONF_* macros.
# CONF_MACHTYPE / LOCALEDIR verified against the strings in Make's
# bash_5.2.37-2_amd64.deb (x86_64-pc-linux-gnu, /usr/share/locale).
SYSTEM_FLAGS = {
    "PROGRAM": "bash",
    "CONF_HOSTTYPE": "x86_64",
    "CONF_OSTYPE": "linux-gnu",
    "CONF_MACHTYPE": "x86_64-pc-linux-gnu",
    "CONF_VENDOR": "pc",
    "LOCALEDIR": "/usr/share/locale",
    "PACKAGE": "bash",
}
