"""The update-alternatives symlinks dpkg postinst would create.

The deb layers unpack data tars without running maintainer scripts, so the
alternatives system never runs; these are the links a Make image ends up with
(read from fsroot-vs, the build baseline), minus bash-builtins.7.gz, whose
target is a man page this image strips. The regulatory.db entries point at
/lib/firmware/..., which resolves through the usr-merge /lib -> usr/lib
symlink.

Two link levels, exactly as update-alternatives lays them out:
  /usr/bin/<generic>          -> /etc/alternatives/<generic>
  /etc/alternatives/<generic> -> the selected real implementation
"""

# /etc/alternatives/<name> -> target
ALTERNATIVES = {
    'arptables': '/usr/sbin/arptables-nft',
    'arptables-restore': '/usr/sbin/arptables-nft-restore',
    'arptables-save': '/usr/sbin/arptables-nft-save',
    'awk': '/usr/bin/mawk',
    'awk.1.gz': '/usr/share/man/man1/mawk.1.gz',
    'ebtables': '/usr/sbin/ebtables-nft',
    'ebtables-restore': '/usr/sbin/ebtables-nft-restore',
    'ebtables-save': '/usr/sbin/ebtables-nft-save',
    'editor': '/usr/bin/vim.basic',
    'editor.1.gz': '/usr/share/man/man1/vim.1.gz',
    'editor.da.1.gz': '/usr/share/man/da/man1/vim.1.gz',
    'editor.de.1.gz': '/usr/share/man/de/man1/vim.1.gz',
    'editor.fr.1.gz': '/usr/share/man/fr/man1/vim.1.gz',
    'editor.it.1.gz': '/usr/share/man/it/man1/vim.1.gz',
    'editor.ja.1.gz': '/usr/share/man/ja/man1/vim.1.gz',
    'editor.pl.1.gz': '/usr/share/man/pl/man1/vim.1.gz',
    'editor.ru.1.gz': '/usr/share/man/ru/man1/vim.1.gz',
    'editor.tr.1.gz': '/usr/share/man/tr/man1/vim.1.gz',
    'ex': '/usr/bin/vim.basic',
    'ex.1.gz': '/usr/share/man/man1/vim.1.gz',
    'ex.da.1.gz': '/usr/share/man/da/man1/vim.1.gz',
    'ex.de.1.gz': '/usr/share/man/de/man1/vim.1.gz',
    'ex.fr.1.gz': '/usr/share/man/fr/man1/vim.1.gz',
    'ex.it.1.gz': '/usr/share/man/it/man1/vim.1.gz',
    'ex.ja.1.gz': '/usr/share/man/ja/man1/vim.1.gz',
    'ex.pl.1.gz': '/usr/share/man/pl/man1/vim.1.gz',
    'ex.ru.1.gz': '/usr/share/man/ru/man1/vim.1.gz',
    'ex.tr.1.gz': '/usr/share/man/tr/man1/vim.1.gz',
    'ip6tables': '/usr/sbin/ip6tables-nft',
    'ip6tables-restore': '/usr/sbin/ip6tables-nft-restore',
    'ip6tables-save': '/usr/sbin/ip6tables-nft-save',
    'iptables': '/usr/sbin/iptables-nft',
    'iptables-restore': '/usr/sbin/iptables-nft-restore',
    'iptables-save': '/usr/sbin/iptables-nft-save',
    'lft': '/usr/bin/lft.db',
    'lft.1.gz': '/usr/share/man/man1/lft.db.1.gz',
    'lzcat': '/usr/bin/xzcat',
    'lzcat.1.gz': '/usr/share/man/man1/xzcat.1.gz',
    'lzcmp': '/usr/bin/xzcmp',
    'lzcmp.1.gz': '/usr/share/man/man1/xzcmp.1.gz',
    'lzdiff': '/usr/bin/xzdiff',
    'lzdiff.1.gz': '/usr/share/man/man1/xzdiff.1.gz',
    'lzegrep': '/usr/bin/xzegrep',
    'lzegrep.1.gz': '/usr/share/man/man1/xzegrep.1.gz',
    'lzfgrep': '/usr/bin/xzfgrep',
    'lzfgrep.1.gz': '/usr/share/man/man1/xzfgrep.1.gz',
    'lzgrep': '/usr/bin/xzgrep',
    'lzgrep.1.gz': '/usr/share/man/man1/xzgrep.1.gz',
    'lzless': '/usr/bin/xzless',
    'lzless.1.gz': '/usr/share/man/man1/xzless.1.gz',
    'lzma': '/usr/bin/xz',
    'lzma.1.gz': '/usr/share/man/man1/xz.1.gz',
    'lzmore': '/usr/bin/xzmore',
    'lzmore.1.gz': '/usr/share/man/man1/xzmore.1.gz',
    'mt': '/usr/bin/mt-gnu',
    'mt.1.gz': '/usr/share/man/man1/mt-gnu.1.gz',
    'nawk': '/usr/bin/mawk',
    'nawk.1.gz': '/usr/share/man/man1/mawk.1.gz',
    'pager': '/usr/bin/less',
    'pager.1.gz': '/usr/share/man/man1/less.1.gz',
    'regulatory.db': '/lib/firmware/regulatory.db-debian',
    'regulatory.db.p7s': '/lib/firmware/regulatory.db.p7s-debian',
    'rmt': '/usr/sbin/rmt-tar',
    'rmt.8.gz': '/usr/share/man/man8/rmt-tar.8.gz',
    'rview': '/usr/bin/vim.basic',
    'rvim': '/usr/bin/vim.basic',
    'sar': '/usr/bin/sar.sysstat',
    'sar.1.gz': '/usr/share/man/man1/sar.sysstat.1.gz',
    'tcptraceroute': '/usr/bin/tcptraceroute.mt',
    'tcptraceroute.1.gz': '/usr/share/man/man1/tcptraceroute.mt.1.gz',
    'traceproto': '/usr/bin/traceproto.db',
    'traceproto.1.gz': '/usr/share/man/man1/traceproto.db.1.gz',
    'traceroute': '/usr/bin/traceroute.db',
    'traceroute.1.gz': '/usr/share/man/man1/traceroute.db.1.gz',
    'traceroute.sbin': '/usr/bin/traceroute.db',
    'traceroute6': '/usr/bin/rltraceroute6',
    'traceroute6.8.gz': '/usr/share/man/man8/rltraceroute6.8.gz',
    'unlzma': '/usr/bin/unxz',
    'unlzma.1.gz': '/usr/share/man/man1/unxz.1.gz',
    'vi': '/usr/bin/vim.basic',
    'vi.1.gz': '/usr/share/man/man1/vim.1.gz',
    'vi.da.1.gz': '/usr/share/man/da/man1/vim.1.gz',
    'vi.de.1.gz': '/usr/share/man/de/man1/vim.1.gz',
    'vi.fr.1.gz': '/usr/share/man/fr/man1/vim.1.gz',
    'vi.it.1.gz': '/usr/share/man/it/man1/vim.1.gz',
    'vi.ja.1.gz': '/usr/share/man/ja/man1/vim.1.gz',
    'vi.pl.1.gz': '/usr/share/man/pl/man1/vim.1.gz',
    'vi.ru.1.gz': '/usr/share/man/ru/man1/vim.1.gz',
    'vi.tr.1.gz': '/usr/share/man/tr/man1/vim.1.gz',
    'view': '/usr/bin/vim.basic',
    'view.1.gz': '/usr/share/man/man1/vim.1.gz',
    'view.da.1.gz': '/usr/share/man/da/man1/vim.1.gz',
    'view.de.1.gz': '/usr/share/man/de/man1/vim.1.gz',
    'view.fr.1.gz': '/usr/share/man/fr/man1/vim.1.gz',
    'view.it.1.gz': '/usr/share/man/it/man1/vim.1.gz',
    'view.ja.1.gz': '/usr/share/man/ja/man1/vim.1.gz',
    'view.pl.1.gz': '/usr/share/man/pl/man1/vim.1.gz',
    'view.ru.1.gz': '/usr/share/man/ru/man1/vim.1.gz',
    'view.tr.1.gz': '/usr/share/man/tr/man1/vim.1.gz',
    'vim': '/usr/bin/vim.basic',
    'vimdiff': '/usr/bin/vim.basic',
    'which': '/usr/bin/which.debianutils',
    'which.1.gz': '/usr/share/man/man1/which.debianutils.1.gz',
    'which.de1.gz': '/usr/share/man/de/man1/which.debianutils.1.gz',
    'which.es1.gz': '/usr/share/man/es/man1/which.debianutils.1.gz',
    'which.fr1.gz': '/usr/share/man/fr/man1/which.debianutils.1.gz',
    'which.it1.gz': '/usr/share/man/it/man1/which.debianutils.1.gz',
    'which.ja1.gz': '/usr/share/man/ja/man1/which.debianutils.1.gz',
    'which.pl1.gz': '/usr/share/man/pl/man1/which.debianutils.1.gz',
    'which.sl1.gz': '/usr/share/man/sl/man1/which.debianutils.1.gz',
}

# generic path -> /etc/alternatives/<name>
ALTERNATIVE_BINS = {
    '/usr/bin/awk': '/etc/alternatives/awk',
    '/usr/bin/editor': '/etc/alternatives/editor',
    '/usr/bin/ex': '/etc/alternatives/ex',
    '/usr/bin/lft': '/etc/alternatives/lft',
    '/usr/bin/lzcat': '/etc/alternatives/lzcat',
    '/usr/bin/lzcmp': '/etc/alternatives/lzcmp',
    '/usr/bin/lzdiff': '/etc/alternatives/lzdiff',
    '/usr/bin/lzegrep': '/etc/alternatives/lzegrep',
    '/usr/bin/lzfgrep': '/etc/alternatives/lzfgrep',
    '/usr/bin/lzgrep': '/etc/alternatives/lzgrep',
    '/usr/bin/lzless': '/etc/alternatives/lzless',
    '/usr/bin/lzma': '/etc/alternatives/lzma',
    '/usr/bin/lzmore': '/etc/alternatives/lzmore',
    '/usr/bin/mt': '/etc/alternatives/mt',
    '/usr/bin/nawk': '/etc/alternatives/nawk',
    '/usr/bin/pager': '/etc/alternatives/pager',
    '/usr/bin/rview': '/etc/alternatives/rview',
    '/usr/bin/rvim': '/etc/alternatives/rvim',
    '/usr/bin/sar': '/etc/alternatives/sar',
    '/usr/bin/tcptraceroute': '/etc/alternatives/tcptraceroute',
    '/usr/bin/traceproto': '/etc/alternatives/traceproto',
    '/usr/bin/traceroute': '/etc/alternatives/traceroute',
    '/usr/bin/traceroute6': '/etc/alternatives/traceroute6',
    '/usr/bin/unlzma': '/etc/alternatives/unlzma',
    '/usr/bin/vi': '/etc/alternatives/vi',
    '/usr/bin/view': '/etc/alternatives/view',
    '/usr/bin/vim': '/etc/alternatives/vim',
    '/usr/bin/vimdiff': '/etc/alternatives/vimdiff',
    '/usr/bin/which': '/etc/alternatives/which',
    '/usr/sbin/arptables': '/etc/alternatives/arptables',
    '/usr/sbin/arptables-restore': '/etc/alternatives/arptables-restore',
    '/usr/sbin/arptables-save': '/etc/alternatives/arptables-save',
    '/usr/sbin/ebtables': '/etc/alternatives/ebtables',
    '/usr/sbin/ebtables-restore': '/etc/alternatives/ebtables-restore',
    '/usr/sbin/ebtables-save': '/etc/alternatives/ebtables-save',
    '/usr/sbin/ip6tables': '/etc/alternatives/ip6tables',
    '/usr/sbin/ip6tables-restore': '/etc/alternatives/ip6tables-restore',
    '/usr/sbin/ip6tables-save': '/etc/alternatives/ip6tables-save',
    '/usr/sbin/iptables': '/etc/alternatives/iptables',
    '/usr/sbin/iptables-restore': '/etc/alternatives/iptables-restore',
    '/usr/sbin/iptables-save': '/etc/alternatives/iptables-save',
    '/usr/sbin/rmt': '/etc/alternatives/rmt',
    '/usr/sbin/traceroute': '/etc/alternatives/traceroute.sbin',
}

