"""deb-systemd-helper's enable bookkeeping under
/var/lib/systemd/deb-systemd-helper-enabled/.

`deb-systemd-helper enable <unit>` (what dh_installsystemd's postinst snippet
calls) records, for each unit it enabled, the exact set of /etc symlinks it
created -- in `<unit>.dsh-also`, one path per line -- plus an empty marker file
per (target.wants, unit) pair. On upgrade the helper reads this back to decide
whether the admin has since disabled the unit: no state means "never enabled by
us", so it re-enables and silently re-starts services the operator turned off.

Bazel never runs the postinst, so the state is reproduced here verbatim from
the Make fsroot. The symlinks themselves live in
//platform/common/rootfs:systemd_enable_layer; this is only the bookkeeping
that keeps a later `apt upgrade` from contradicting it.

DSH_FILES maps the path under deb-systemd-helper-enabled/ to its content
("" for the empty markers).
"""

DSH_FILES = {
    'aaastatsd.timer.dsh-also': '/etc/systemd/system/timers.target.wants/aaastatsd.timer\n/etc/systemd/system/sonic.target.wants/aaastatsd.timer\n',
    'apparmor.service.dsh-also': '/etc/systemd/system/sysinit.target.wants/apparmor.service\n',
    'apt-daily-upgrade.timer.dsh-also': '/etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer\n',
    'apt-daily.timer.dsh-also': '/etc/systemd/system/timers.target.wants/apt-daily.timer\n',
    'audit-rules.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/audit-rules.service\n',
    'auditd.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/auditd.service\n',
    'basic.target.wants/kdump-tools.service': '',
    'basic.target.wants/networking.service': '',
    'caclmgrd.service.dsh-also': '/etc/systemd/system/sonic.target.wants/caclmgrd.service\n',
    'chrony-wait.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/chrony-wait.service\n',
    'chrony.service.dsh-also': '/etc/systemd/system/chronyd.service\n/etc/systemd/system/multi-user.target.wants/chrony.service\n',
    'chronyd-restricted.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/chronyd-restricted.service\n',
    'chronyd.service': '',
    'console-monitor-dce.service.dsh-also': '/etc/systemd/system/sonic.target.wants/console-monitor-dce.service\n',
    'console-monitor-dte.service.dsh-also': '/etc/systemd/system/sonic.target.wants/console-monitor-dte.service\n',
    'containerd.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/containerd.service\n',
    'cron.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/cron.service\n',
    'default.target.wants/nvmefc-boot-connections.service': '',
    'default.target.wants/nvmf-autoconnect.service': '',
    'determine-reboot-cause.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/determine-reboot-cause.service\n',
    'docker.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/docker.service\n',
    'docker.socket.dsh-also': '/etc/systemd/system/sockets.target.wants/docker.socket\n',
    'dpkg-db-backup.timer.dsh-also': '/etc/systemd/system/timers.target.wants/dpkg-db-backup.timer\n',
    'e2scrub_all.timer.dsh-also': '/etc/systemd/system/timers.target.wants/e2scrub_all.timer\n',
    'e2scrub_reap.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/e2scrub_reap.service\n',
    'featured.timer.dsh-also': '/etc/systemd/system/timers.target.wants/featured.timer\n/etc/systemd/system/sonic.target.wants/featured.timer\n',
    'fstrim.timer.dsh-also': '/etc/systemd/system/timers.target.wants/fstrim.timer\n',
    'gnmi.service.wants/sonic-hostservice.service': '',
    'gnoi-shutdown.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/gnoi-shutdown.service\n',
    'grub-common.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/grub-common.service\n/etc/systemd/system/suspend.target.wants/grub-common.service\n/etc/systemd/system/hibernate.target.wants/grub-common.service\n/etc/systemd/system/hybrid-sleep.target.wants/grub-common.service\n/etc/systemd/system/suspend-then-hibernate.target.wants/grub-common.service\n',
    'haveged.service.dsh-also': '/etc/systemd/system/sysinit.target.wants/haveged.service\n',
    'hibernate.target.wants/grub-common.service': '',
    'hostcfgd.timer.dsh-also': '/etc/systemd/system/timers.target.wants/hostcfgd.timer\n/etc/systemd/system/sonic.target.wants/hostcfgd.timer\n',
    'hybrid-sleep.target.wants/grub-common.service': '',
    'kdump-tools.service.dsh-also': '/etc/systemd/system/basic.target.wants/kdump-tools.service\n',
    'logrotate.timer.dsh-also': '/etc/systemd/system/timers.target.wants/logrotate.timer\n',
    'mgmt-framework.service.wants/sonic-hostservice.service': '',
    'monit.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/monit.service\n',
    'multi-user.target.wants/audit-rules.service': '',
    'multi-user.target.wants/auditd.service': '',
    'multi-user.target.wants/chrony.service': '',
    'multi-user.target.wants/containerd.service': '',
    'multi-user.target.wants/cron.service': '',
    'multi-user.target.wants/determine-reboot-cause.service': '',
    'multi-user.target.wants/docker.service': '',
    'multi-user.target.wants/e2scrub_reap.service': '',
    'multi-user.target.wants/gnoi-shutdown.service': '',
    'multi-user.target.wants/grub-common.service': '',
    'multi-user.target.wants/monit.service': '',
    'multi-user.target.wants/netfilter-persistent.service': '',
    'multi-user.target.wants/nslcd.service': '',
    'multi-user.target.wants/process-reboot-cause.service': '',
    'multi-user.target.wants/ras-mc-ctl.service': '',
    'multi-user.target.wants/rasdaemon.service': '',
    'multi-user.target.wants/rsyslog.service': '',
    'multi-user.target.wants/smartmontools.service': '',
    'multi-user.target.wants/ssh.service': '',
    'multi-user.target.wants/sysfsutils.service': '',
    'multi-user.target.wants/sysstat.service': '',
    'netfilter-persistent.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/netfilter-persistent.service\n',
    'network.target.wants/networking.service': '',
    'networking.service.dsh-also': '/etc/systemd/system/basic.target.wants/networking.service\n/etc/systemd/system/network.target.wants/networking.service\n/etc/systemd/system/shutdown.target.wants/networking.service\n',
    'nftables.service.dsh-also': '/etc/systemd/system/sysinit.target.wants/nftables.service\n',
    'nslcd.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/nslcd.service\n',
    'nvmefc-boot-connections.service.dsh-also': '/etc/systemd/system/default.target.wants/nvmefc-boot-connections.service\n',
    'nvmf-autoconnect.service.dsh-also': '/etc/systemd/system/default.target.wants/nvmf-autoconnect.service\n',
    'procdockerstatsd.service.dsh-also': '/etc/systemd/system/sonic.target.wants/procdockerstatsd.service\n',
    'process-reboot-cause.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/process-reboot-cause.service\n',
    'ras-mc-ctl.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/ras-mc-ctl.service\n',
    'rasdaemon.service.dsh-also': '/etc/systemd/system/multi-user.target.wants/rasdaemon.service\n',
    'resolvconf-pull-resolved.path.dsh-also': '/etc/systemd/system/systemd-resolved.service.wants/resolvconf-pull-resolved.path\n',
    'resolvconf-pull-resolved.service.dsh-also': '/etc/systemd/system/systemd-resolved.service.wants/resolvconf-pull-resolved.service\n',
    'resolvconf.service.dsh-also': '/etc/systemd/system/sysinit.target.wants/resolvconf.service\n',
    'rsyslog.service.dsh-also': '/etc/systemd/system/syslog.service\n/etc/systemd/system/multi-user.target.wants/rsyslog.service\n',
    'shutdown.target.wants/networking.service': '',
    'smartd.service': '',
    'smartmontools.service.dsh-also': '/etc/systemd/system/smartd.service\n/etc/systemd/system/multi-user.target.wants/smartmontools.service\n',
    'sockets.target.wants/docker.socket': '',
    'sockets.target.wants/uuidd.socket': '',
    'sonic-hostservice.service.dsh-also': '/etc/systemd/system/mgmt-framework.service.wants/sonic-hostservice.service\n/etc/systemd/system/telemetry.service.wants/sonic-hostservice.service\n/etc/systemd/system/gnmi.service.wants/sonic-hostservice.service\n',
    'sonic.target.wants/aaastatsd.timer': '',
    'sonic.target.wants/caclmgrd.service': '',
    'sonic.target.wants/console-monitor-dce.service': '',
    'sonic.target.wants/console-monitor-dte.service': '',
    'sonic.target.wants/featured.timer': '',
    'sonic.target.wants/hostcfgd.timer': '',
    'sonic.target.wants/procdockerstatsd.service': '',
    'ssh.service.dsh-also': '/etc/systemd/system/sshd.service\n/etc/systemd/system/multi-user.target.wants/ssh.service\n',
    'ssh.service.wants/sshd-keygen.service': '',
    'ssh.socket.dsh-also': '/etc/systemd/system/sockets.target.wants/ssh.socket\n',
    'ssh.socket.wants/sshd-keygen.service': '',
    'sshd-keygen.service.dsh-also': '/etc/systemd/system/ssh.service.wants/sshd-keygen.service\n/etc/systemd/system/sshd.service.wants/sshd-keygen.service\n/etc/systemd/system/sshd@.service.wants/sshd-keygen.service\n/etc/systemd/system/ssh.socket.wants/sshd-keygen.service\n',
    'sshd.service': '',
    'sshd.service.wants/sshd-keygen.service': '',
    'sshd@.service.wants/sshd-keygen.service': '',
    'suspend-then-hibernate.target.wants/grub-common.service': '',
    'suspend.target.wants/grub-common.service': '',
    'sysfs.service': '',
    'sysfsutils.service.dsh-also': '/etc/systemd/system/sysfs.service\n/etc/systemd/system/multi-user.target.wants/sysfsutils.service\n',
    'sysinit.target.wants/apparmor.service': '',
    'sysinit.target.wants/haveged.service': '',
    'sysinit.target.wants/resolvconf.service': '',
    'syslog.service': '',
    'sysstat-collect.timer.dsh-also': '/etc/systemd/system/sysstat.service.wants/sysstat-collect.timer\n',
    'sysstat-rotate.timer.dsh-also': '/etc/systemd/system/sysstat.service.wants/sysstat-rotate.timer\n',
    'sysstat-summary.timer.dsh-also': '/etc/systemd/system/sysstat.service.wants/sysstat-summary.timer\n',
    'sysstat.service.dsh-also': '/etc/systemd/system/sysstat.service.wants/sysstat-collect.timer\n/etc/systemd/system/sysstat.service.wants/sysstat-summary.timer\n/etc/systemd/system/sysstat.service.wants/sysstat-rotate.timer\n/etc/systemd/system/multi-user.target.wants/sysstat.service\n',
    'sysstat.service.wants/sysstat-collect.timer': '',
    'sysstat.service.wants/sysstat-rotate.timer': '',
    'sysstat.service.wants/sysstat-summary.timer': '',
    'systemd-bootchart.service.dsh-also': '/etc/systemd/system/sysinit.target.wants/systemd-bootchart.service\n',
    'systemd-resolved.service.wants/resolvconf-pull-resolved.path': '',
    'systemd-resolved.service.wants/resolvconf-pull-resolved.service': '',
    'telemetry.service.wants/sonic-hostservice.service': '',
    'timers.target.wants/aaastatsd.timer': '',
    'timers.target.wants/apt-daily-upgrade.timer': '',
    'timers.target.wants/apt-daily.timer': '',
    'timers.target.wants/dpkg-db-backup.timer': '',
    'timers.target.wants/e2scrub_all.timer': '',
    'timers.target.wants/featured.timer': '',
    'timers.target.wants/fstrim.timer': '',
    'timers.target.wants/hostcfgd.timer': '',
    'timers.target.wants/logrotate.timer': '',
    'uuidd.service.dsh-also': '/etc/systemd/system/sockets.target.wants/uuidd.socket\n',
    'uuidd.socket.dsh-also': '/etc/systemd/system/sockets.target.wants/uuidd.socket\n',
}
