"""SysV rc*.d symlinks that Make's image gets from each package's
`update-rc.d <svc> defaults` postinst call (insserv computes S01/K01 from the
init.d LSB headers). deb layers unpack data tars without running maintainer
scripts, so the resulting links are pinned here verbatim from fsroot-vs ground
truth. Every target is ../init.d/<name>; the link basename encodes the
insserv-computed action (S=start, K=stop) and sequence number.

Notable: rasdaemon carries K01 links in runlevels 2-5 because its postinst
enables only the systemd unit (`update-rc.d rasdaemon defaults` is followed by
`update-rc.d rasdaemon disable` semantics in insserv's dependency output).
"""

# /etc/rcN.d/<link> -> ../init.d/<service>  (link basename implies service)
RCD_LINKS = [
    ("/etc/rc0.d/K01auditd", "../init.d/auditd"),
    ("/etc/rc0.d/K01chrony", "../init.d/chrony"),
    ("/etc/rc0.d/K01docker", "../init.d/docker"),
    ("/etc/rc0.d/K01monit", "../init.d/monit"),
    ("/etc/rc0.d/K01netfilter-persistent", "../init.d/netfilter-persistent"),
    ("/etc/rc0.d/K01nslcd", "../init.d/nslcd"),
    ("/etc/rc0.d/K01resolvconf", "../init.d/resolvconf"),
    ("/etc/rc0.d/K01smartmontools", "../init.d/smartmontools"),
    ("/etc/rc0.d/K01uuidd", "../init.d/uuidd"),
    ("/etc/rc1.d/K01auditd", "../init.d/auditd"),
    ("/etc/rc1.d/K01chrony", "../init.d/chrony"),
    ("/etc/rc1.d/K01docker", "../init.d/docker"),
    ("/etc/rc1.d/K01monit", "../init.d/monit"),
    ("/etc/rc1.d/K01netfilter-persistent", "../init.d/netfilter-persistent"),
    ("/etc/rc1.d/K01nslcd", "../init.d/nslcd"),
    ("/etc/rc1.d/K01smartmontools", "../init.d/smartmontools"),
    ("/etc/rc1.d/K01uuidd", "../init.d/uuidd"),
    ("/etc/rc2.d/K01rasdaemon", "../init.d/rasdaemon"),
    ("/etc/rc2.d/S01auditd", "../init.d/auditd"),
    ("/etc/rc2.d/S01chrony", "../init.d/chrony"),
    ("/etc/rc2.d/S01cron", "../init.d/cron"),
    ("/etc/rc2.d/S01dbus", "../init.d/dbus"),
    ("/etc/rc2.d/S01docker", "../init.d/docker"),
    ("/etc/rc2.d/S01kdump-tools", "../init.d/kdump-tools"),
    ("/etc/rc2.d/S01monit", "../init.d/monit"),
    ("/etc/rc2.d/S01nslcd", "../init.d/nslcd"),
    ("/etc/rc2.d/S01smartmontools", "../init.d/smartmontools"),
    ("/etc/rc2.d/S01ssh", "../init.d/ssh"),
    ("/etc/rc2.d/S01sudo", "../init.d/sudo"),
    ("/etc/rc2.d/S01sysfsutils", "../init.d/sysfsutils"),
    ("/etc/rc2.d/S01sysstat", "../init.d/sysstat"),
    ("/etc/rc2.d/S01uuidd", "../init.d/uuidd"),
    ("/etc/rc3.d/K01rasdaemon", "../init.d/rasdaemon"),
    ("/etc/rc3.d/S01auditd", "../init.d/auditd"),
    ("/etc/rc3.d/S01chrony", "../init.d/chrony"),
    ("/etc/rc3.d/S01cron", "../init.d/cron"),
    ("/etc/rc3.d/S01dbus", "../init.d/dbus"),
    ("/etc/rc3.d/S01docker", "../init.d/docker"),
    ("/etc/rc3.d/S01kdump-tools", "../init.d/kdump-tools"),
    ("/etc/rc3.d/S01monit", "../init.d/monit"),
    ("/etc/rc3.d/S01nslcd", "../init.d/nslcd"),
    ("/etc/rc3.d/S01smartmontools", "../init.d/smartmontools"),
    ("/etc/rc3.d/S01ssh", "../init.d/ssh"),
    ("/etc/rc3.d/S01sudo", "../init.d/sudo"),
    ("/etc/rc3.d/S01sysfsutils", "../init.d/sysfsutils"),
    ("/etc/rc3.d/S01sysstat", "../init.d/sysstat"),
    ("/etc/rc3.d/S01uuidd", "../init.d/uuidd"),
    ("/etc/rc4.d/K01rasdaemon", "../init.d/rasdaemon"),
    ("/etc/rc4.d/S01auditd", "../init.d/auditd"),
    ("/etc/rc4.d/S01chrony", "../init.d/chrony"),
    ("/etc/rc4.d/S01cron", "../init.d/cron"),
    ("/etc/rc4.d/S01dbus", "../init.d/dbus"),
    ("/etc/rc4.d/S01docker", "../init.d/docker"),
    ("/etc/rc4.d/S01kdump-tools", "../init.d/kdump-tools"),
    ("/etc/rc4.d/S01monit", "../init.d/monit"),
    ("/etc/rc4.d/S01nslcd", "../init.d/nslcd"),
    ("/etc/rc4.d/S01smartmontools", "../init.d/smartmontools"),
    ("/etc/rc4.d/S01ssh", "../init.d/ssh"),
    ("/etc/rc4.d/S01sudo", "../init.d/sudo"),
    ("/etc/rc4.d/S01sysfsutils", "../init.d/sysfsutils"),
    ("/etc/rc4.d/S01sysstat", "../init.d/sysstat"),
    ("/etc/rc4.d/S01uuidd", "../init.d/uuidd"),
    ("/etc/rc5.d/K01rasdaemon", "../init.d/rasdaemon"),
    ("/etc/rc5.d/S01auditd", "../init.d/auditd"),
    ("/etc/rc5.d/S01chrony", "../init.d/chrony"),
    ("/etc/rc5.d/S01cron", "../init.d/cron"),
    ("/etc/rc5.d/S01dbus", "../init.d/dbus"),
    ("/etc/rc5.d/S01docker", "../init.d/docker"),
    ("/etc/rc5.d/S01kdump-tools", "../init.d/kdump-tools"),
    ("/etc/rc5.d/S01monit", "../init.d/monit"),
    ("/etc/rc5.d/S01nslcd", "../init.d/nslcd"),
    ("/etc/rc5.d/S01smartmontools", "../init.d/smartmontools"),
    ("/etc/rc5.d/S01ssh", "../init.d/ssh"),
    ("/etc/rc5.d/S01sudo", "../init.d/sudo"),
    ("/etc/rc5.d/S01sysfsutils", "../init.d/sysfsutils"),
    ("/etc/rc5.d/S01sysstat", "../init.d/sysstat"),
    ("/etc/rc5.d/S01uuidd", "../init.d/uuidd"),
    ("/etc/rc6.d/K01auditd", "../init.d/auditd"),
    ("/etc/rc6.d/K01chrony", "../init.d/chrony"),
    ("/etc/rc6.d/K01docker", "../init.d/docker"),
    ("/etc/rc6.d/K01monit", "../init.d/monit"),
    ("/etc/rc6.d/K01netfilter-persistent", "../init.d/netfilter-persistent"),
    ("/etc/rc6.d/K01nslcd", "../init.d/nslcd"),
    ("/etc/rc6.d/K01resolvconf", "../init.d/resolvconf"),
    ("/etc/rc6.d/K01smartmontools", "../init.d/smartmontools"),
    ("/etc/rc6.d/K01uuidd", "../init.d/uuidd"),
    ("/etc/rcS.d/K01resolvconf", "../init.d/resolvconf"),
    ("/etc/rcS.d/S01apparmor", "../init.d/apparmor"),
    ("/etc/rcS.d/S01netfilter-persistent", "../init.d/netfilter-persistent"),
    ("/etc/rcS.d/S01procps", "../init.d/procps"),
    ("/etc/rcS.d/S01screen-cleanup", "../init.d/screen-cleanup"),
    ("/etc/rcS.d/S01x11-common", "../init.d/x11-common"),
]
