#!/bin/sh
set -e

rm -f /etc/frr/.pkg.frr.nointegrated

if [ "$1" = "purge" ]; then
	rm -rf /run/frr || true

	# "purge" does not remove logfiles.  therefore we shouldn't delete
	# the "frr" user/group since that would leave files with "dangling"
	# ownership.
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/frr" ] ; then
	chmod -x "/etc/init.d/frr" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d frr remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'frr.service' >/dev/null || true
	fi
fi
# End automatically added section

