"""Autoconf substitutions for monit 5.34.3 on x86_64 Debian trixie (glibc).

Stands in for ./configure, which probes the host compiler and libc. Values match
what autoconf resolves with the flags debian/rules passes
(--sysconfdir=/etc/monit --with-ipv6).

Applied to the tarball's own src/config.h.in by the genrule in BUILD.bazel;
macros absent here stay #undef.
"""

CONFIG_DEFINES = {
    "HAVE_ALLOCA_H": "1",
    "HAVE_ARPA_INET_H": "1",
    "HAVE_ASM_PARAM_H": "1",
    "HAVE_ASN1_TIME_DIFF": "1",
    "HAVE_BACKTRACE": "1",
    "HAVE_CRYPT_H": "1",
    "HAVE_CTYPE_H": "1",
    "HAVE_DIRENT_H": "1",
    "HAVE_DLFCN_H": "1",
    "HAVE_EC_KEY": "1",
    "HAVE_ERRNO_H": "1",
    "HAVE_EXECINFO_H": "1",
    "HAVE_FCNTL_H": "1",
    "HAVE_FORK": "1",
    "HAVE_GETADDRINFO": "1",
    "HAVE_GETLOADAVG": "1",
    "HAVE_GETOPT_H": "1",
    "HAVE_GETOPT_LONG": "1",
    "HAVE_GLOB_H": "1",
    "HAVE_GRP_H": "1",
    "HAVE_IFADDRS_H": "1",
    "HAVE_INTTYPES_H": "1",
    "HAVE_IPV6": "1",
    "HAVE_LARGEFILES": "1",
    "HAVE_LIBCRYPT": "1",
    "HAVE_LIBCRYPTO": "1",
    "HAVE_LIBNSL": "1",
    "HAVE_LIBPAM": "1",
    "HAVE_LIBPTHREAD": "1",
    "HAVE_LIBRESOLV": "1",
    "HAVE_LIBSSL": "1",
    "HAVE_LIBZ": "1",
    "HAVE_LIMITS_H": "1",
    "HAVE_LOCALE_H": "1",
    "HAVE_MEMORY_H": "1",
    "HAVE_MNTENT_H": "1",
    "HAVE_MTAB": "1",
    "HAVE_NETDB_H": "1",
    "HAVE_NETINET_ICMP6_H": "1",
    "HAVE_NETINET_IN_H": "1",
    "HAVE_NETINET_IN_SYSTM_H": "1",
    "HAVE_NETINET_IP_H": "1",
    "HAVE_NETINET_IP_ICMP_H": "1",
    "HAVE_NETINET_TCP_H": "1",
    "HAVE_NET_IF_H": "1",
    "HAVE_NET_ROUTE_H": "1",
    "HAVE_OPENSSL": "1",
    "HAVE_PATHS_H": "1",
    "HAVE_POLL_H": "1",
    "HAVE_PTHREAD_H": "1",
    "HAVE_PWD_H": "1",
    "HAVE_REGEX_H": "1",
    "HAVE_SECURITY_PAM_APPL_H": "1",
    "HAVE_SETJMP_H": "1",
    "HAVE_SETLOCALE": "1",
    "HAVE_SIGNAL_H": "1",
    "HAVE_SSL_CTX_SET_KEYLOG_CALLBACK": "1",
    "HAVE_STATFS": "1",
    "HAVE_STATVFS": "1",
    "HAVE_STDARG_H": "1",
    "HAVE_STDBOOL_H": "1",
    "HAVE_STDDEF_H": "1",
    "HAVE_STDINT_H": "1",
    "HAVE_STDIO_H": "1",
    "HAVE_STDLIB_H": "1",
    "HAVE_STRFTIME": "1",
    "HAVE_STRINGS_H": "1",
    "HAVE_STRING_H": "1",
    "HAVE_SYSLOG": "1",
    "HAVE_SYSLOG_H": "1",
    "HAVE_SYS_IOCTL_H": "1",
    "HAVE_SYS_MOUNT_H": "1",
    "HAVE_SYS_PARAM_H": "1",
    "HAVE_SYS_PROCFS_H": "1",
    "HAVE_SYS_QUEUE_H": "1",
    "HAVE_SYS_RESOURCE_H": "1",
    "HAVE_SYS_SOCKET_H": "1",
    "HAVE_SYS_STATFS_H": "1",
    "HAVE_SYS_STATVFS_H": "1",
    "HAVE_SYS_STAT_H": "1",
    "HAVE_SYS_SWAP_H": "1",
    "HAVE_SYS_SYSINFO_H": "1",
    "HAVE_SYS_SYSMACROS_H": "1",
    "HAVE_SYS_TIME_H": "1",
    "HAVE_SYS_TYPES_H": "1",
    "HAVE_SYS_UN_H": "1",
    "HAVE_SYS_USER_H": "1",
    "HAVE_SYS_UTSNAME_H": "1",
    "HAVE_SYS_VFS_H": "1",
    "HAVE_SYS_WAIT_H": "1",
    "HAVE_TLSV1_1": "1",
    "HAVE_TLSV1_2": "1",
    "HAVE_TLSV1_3": "1",
    "HAVE_UNISTD_H": "1",
    "HAVE_UTMPX_H": "1",
    "HAVE_VFORK": "1",
    "HAVE_VSYSLOG": "1",
    "HAVE_WORKING_FORK": "1",
    "HAVE_WORKING_VFORK": "1",
    "HAVE_ZLIB_H": "1",
    "LSTAT_FOLLOWS_SLASHED_SYMLINK": "1",
    "LT_OBJDIR": "\".libs/\"",
    "PACKAGE": "\"monit\"",
    "PACKAGE_BUGREPORT": "\"monit-general@nongnu.org\"",
    "PACKAGE_NAME": "\"monit\"",
    "PACKAGE_STRING": "\"monit 5.34.3\"",
    "PACKAGE_TARNAME": "\"monit\"",
    "PACKAGE_URL": "\"\"",
    "PACKAGE_VERSION": "\"5.34.3\"",
    "PIDDIR": "\"/run\"",
    "STDC_HEADERS": "1",
    "VERSION": "\"5.34.3\"",
}

# libmonit/src/xconfig.h.in — libmonit has its own separate autoconf header.
XCONFIG_DEFINES = {
    "HAVE_ARC4RANDOM_BUF": "1",
    "HAVE_CLOCK_GETTIME": "1",
    "HAVE_CTYPE_H": "1",
    "HAVE_DECL_SETJMP": "1",
    "HAVE_DLFCN_H": "1",
    "HAVE_ERRNO_H": "1",
    "HAVE_EXECINFO_H": "1",
    "HAVE_FCNTL_H": "1",
    "HAVE_GETGROUPLIST": "1",
    "HAVE_GETRANDOM": "1",
    "HAVE_IFADDRS_H": "1",
    "HAVE_INTTYPES_H": "1",
    "HAVE_IPV6": "1",
    "HAVE_LIBM": "1",
    "HAVE_LIBPTHREAD": "1",
    "HAVE_LIBZ": "1",
    "HAVE_LIMITS_H": "1",
    "HAVE_NETINET_IN_H": "1",
    "HAVE_NET_IF_H": "1",
    "HAVE_NET_ROUTE_H": "1",
    "HAVE_POLL_H": "1",
    "HAVE_PTHREAD_H": "1",
    "HAVE_SETJMP_H": "1",
    "HAVE_SIGNAL_H": "1",
    "HAVE_STDARG_H": "1",
    "HAVE_STDBOOL_H": "1",
    "HAVE_STDINT_H": "1",
    "HAVE_STDIO_H": "1",
    "HAVE_STDLIB_H": "1",
    "HAVE_STRINGS_H": "1",
    "HAVE_STRING_H": "1",
    "HAVE_SYS_IOCTL_H": "1",
    "HAVE_SYS_POLL_H": "1",
    "HAVE_SYS_RANDOM_H": "1",
    "HAVE_SYS_SENDFILE_H": "1",
    "HAVE_SYS_SOCKET_H": "1",
    "HAVE_SYS_STAT_H": "1",
    "HAVE_SYS_TIME_H": "1",
    "HAVE_SYS_TYPES_H": "1",
    "HAVE_TIMEGM": "1",
    "HAVE_UNISTD_H": "1",
    "HAVE_ZLIB_H": "1",
    "LINUX": "1",
    "LT_OBJDIR": "\".libs/\"",
    "PACKAGE": "\"libmonit\"",
    "PACKAGE_BUGREPORT": "\"monit-dev@tildeslash.com\"",
    "PACKAGE_NAME": "\"libmonit\"",
    "PACKAGE_STRING": "\"libmonit 1.0\"",
    "PACKAGE_TARNAME": "\"libmonit\"",
    "PACKAGE_URL": "\"\"",
    "PACKAGE_VERSION": "\"1.0\"",
    "STDC_HEADERS": "1",
    "VERSION": "\"1.0\"",
}

# Makefile.am substitutes src/{device,process}/sysdep_@ARCH@.c, and
# AM_CPPFLAGS passes the same name as a bare -D<ARCH>.
ARCH = "LINUX"

# AM_CPPFLAGS: -DSYSCONFDIR="\"/etc/monit\"", from debian/rules'
# --sysconfdir=/etc/monit.
SYSCONFDIR = "/etc/monit"

def config_h_cmd(defines):
    """genrule cmd: fill a <header>.in template from a substitution table."""
    return "sed " + " ".join([
        "-e 's|^#undef {name}$$|#define {name} {value}|'".format(
            name = name,
            value = value,
        )
        for name, value in defines.items()
    ] + [
        "-e 's|^#undef \\(.*\\)$$|/* #undef \\1 */|'",
    ]) + " $< > $@"
